---
name: dbus-signature-pyparsing weekly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 20 1 * * 6
  workflow_dispatch:

jobs:
  next-fedora-python-checks:
    strategy:
      matrix:
        include:
          - dependencies: black python3-isort
            task: make -f Makefile fmt-travis
          - dependencies: yamllint
            task: make -f Makefile yamllint
          - dependencies: pylint python3-pyparsing python-hypothesis
            task: >
              PYTHONPATH=./src:/github/home/.local/lib/python3.12/site-packages
              make -f Makefile lint
    runs-on: ubuntu-latest
    container: fedora:40  # NEXT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: >
          dnf install -y
          make
          pip
          ${{ matrix.dependencies }}
      - name: Install hs-dbus-signature
        run: pip install --user hs-dbus-signature
      - name: ${{ matrix.task }}
        run: ${{ matrix.task }}
